### ISSUE TITLE
Switch to lowercase POS tags

### ISSUE THREAD

**Issue by samplereality** [dhowe/RiTaJSHistory#14]
Not sure if this is a bug or not, but I noticed the most recent version of rita.js switched from using uppercase POS tags to lowercase POS tags. For example, whereas in previous versions of rita.js (in Node), you would use 

```
 noun = lexicon.randomWord('NN',2);
```

now you have to use

```
 noun = lexicon.randomWord('nn',2);
```

Otherwise you'll get nothing for the variable noun. Not a big deal, but it did make many of my bots fail until I figured out what was going on!

**Comment by dhowe** [comment]
looking into it... thanks :]

**Comment by dhowe** [comment]
The change that caused this had some unintended consequences (as you found out), which weren't caught in the tests, but this will be the (simpler) behavior moving forward...
