### ISSUE TITLE
textTo(newText, seconds, startTime) different from API

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/RiTaJSHistory#21]
see color-and-fade.html
textTo(newText, seconds) works fine
textTo(newText, seconds,startTime) in API
but
textTo(newText, seconds, endAlpha) in rita.js

**Comment by dhowe** [comment]
should both use: textTo(newText, seconds, startTime) in API

**Comment by kennyviperhk** [comment]
Text not appear after fade out

**Comment by kennyviperhk** [comment]
it works now
