### ISSUE TITLE
Text overlapped on createlines

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/RiTaJSHistory#29]
g_CreateLinesAndLayoutWithBreaks.html , the second coulmn
![screen shot 2014-06-24 at 5 18 21 pm](https://cloud.githubusercontent.com/assets/4047303/3369412/cee972be-fb80-11e3-9cf0-4acc39b95e7e.png)

**Comment by dhowe** [comment]
fixed -- please verify and close

**Comment by kennyviperhk** [comment]
![screen shot 2014-08-05 at 8 06 09 pm](https://cloud.githubusercontent.com/assets/4047303/3811002/ef29b104-1c98-11e4-9879-9f65e80dea18.png)

text disappeared...

**Comment by dhowe** [comment]
did you test this with the current rita?

**Comment by kennyviperhk** [comment]
yes

**Comment by dhowe** [comment]
on holding pending renderer removal
