### ISSUE TITLE
createWords,createLetters not aligned correctly

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/RiTaJSHistory#32]
![screen shot 2014-06-25 at 3 31 05 pm](https://cloud.githubusercontent.com/assets/4047303/3382548/24d3ab44-fc3b-11e3-81f7-4b93ed72011d.png)

g_WordsLettersLines.html

**Comment by dhowe** [comment]
Please be more specific about this... I'm not sure what the problem is

**Comment by kennyviperhk** [comment]
Failed
![screen shot 2014-08-05 at 5 44 41 pm](https://cloud.githubusercontent.com/assets/4047303/3810978/74276a00-1c98-11e4-9f86-7a2af880a3a4.png)

Correct
![screen shot 2014-08-05 at 5 43 20 pm](https://cloud.githubusercontent.com/assets/4047303/3810979/7449cdfc-1c98-11e4-8be0-0ea4fda446cb.png)

RiText.createWords(this, txt, 64, 80); // words
RiText.createLetters(this, txt, 64, 130); // letters

**Comment by dhowe** [comment]
This is not a great test. Its not clear, from looking at it, what the intended output is. How is it failing?

**Comment by kennyviperhk** [comment]
intended output is the second picture

**Comment by dhowe** [comment]
on holding pending renderer removal
