### ISSUE TITLE
Question about build process

### ISSUE THREAD

**Issue by dariusk** [dhowe/RiTaJSHistory#40]
Hi! I'm excited to start contributing to this library (I currently manage [a part of speech lib](https://github.com/dariusk/pos-js)).

I've cloned the repo, installed dependencies, and I just ran `gulp build`. This is the state of my repo after running the build:

``` bash
    modified:   dist/node/rita/README.md
    deleted:    dist/node/rita/doc/PennTags.html
    deleted:    dist/node/rita/doc/PhonemeTags.html
    modified:   dist/node/rita/gulpfile.js
    modified:   dist/rita-1.0.68.micro.js
    modified:   dist/rita-1.0.68.microp5.js
```

The Node dist readme has this diff:

``` diff
-* Web Site:          http://rednoise.org/rita/js
-* Github Repo:       https://github.com/dhowe/RiTaJS/
-* Bug Tracker:       https://github.com/dhowe/RiTaJS/issues
+* Web Site:          http://rednoise.org/rita
+* Github Repo:       https://github.com/dhowe/RiTaJS
+* Bug Tracker:       https://github.com/dhowe/RiTa/issues
```

The `gulpfile` in the Node dist has this diff:

``` diff
-// Clean the build dir
+// Create links to each 'latest'
```

And I can't easily tell what changed in the diffs for the micro js distribution files since they're minified.

Is there an outdated node build in the master branch? I'm afraid to start contributing until `gulp build` on a branch with no changes doesn't change the state of the distribution files.

**Comment by dariusk** [comment]
Actually, for that matter, should `dist/` even be in the repo? Looks like it was added by mistake. I filed PR #41 to fix the issue.

**Comment by dhowe** [comment]
Good catch, Darius. Please note that we are currently filing RiTaJS issues under the [RiTa project](https://github.com/dhowe/RiTa/labels/RiTaJS), using the label "RiTaJS", as there are issues that span both projects (which share a common API)...

Looking forward to your contributions!
