### ISSUE TITLE
RiGrammar.print()

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/RiTaJSHistory#6]
Different output in RiTa and RiTaJS

**Comment by dhowe** [comment]
lets add the differing output(s) and make a test-case

**Comment by dhowe** [comment]
We need to compare the output of the RiGrammar.print() function in RiTa and RiTaJS.
- Use an example in RiGrammar-tests (.java/.js) to load the same grammar file in RiTa and RiTaJS, then call myGrammar.print() for each.
- Post both outputs here if they are different.

**Comment by dhowe** [comment]
Moving to RiTa
